dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: src/Lavalink4NET.sln
mono: none
script:
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - cd src
 - dotnet restore
 - dotnet build