dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
solution: src/Lavalink4NET.sln
mono: none
script:
 - export DOTNET_CLI_TELEMETRY_OPTOUT=1
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - cd src
 - dotnet restore
 - dotnet build
 - dotnet test Lavalink4NET.Tests/Lavalink4NET.Tests.csproj -f netcoreapp3.0